stackclient: stackclient.o stackADT3.o
	gcc -o stackclient.out stackclient.o stackADT3.o

stackclient.o: stackclient.c stackADT.h
	gcc -c stackclient.c

stackADT3.o: stackADT3.c stackADT.h
	gcc -c stackADT3.c
